=== alexgeorgiew/XML_Project_FMI/validation.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ENTITY godfatherpic "images/TheGodfather.jpg">
<!ENTITY titanicpic "images/Titanic.jpg">
<!ENTITY kingkongpic "images/KingKong.jpg">
<!ENTITY rockypic "images/Rocky.jpg">
<!ENTITY meetjoeblackpic "images/MeetJoeBlack.jpg">
<!ENTITY gottipic "images/Gotti.jpg">
<!ENTITY scarfacepic "images/Scarface.jpg">
<!ENTITY dangalpic "images/Dangal.jpg">

<!ELEMENT movies (movie+,alldirectors,allstudios)>
<!ELEMENT movie (title,image,year,genre,production,directorref,movie-stars)>

<!ELEMENT title (#PCDATA)>
<!ELEMENT image (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT genre (#PCDATA)>

<!ELEMENT production (studioref,cost)>
<!ELEMENT studioref (#PCDATA)>
<!ATTLIST studioref target IDREF #REQUIRED>
<!ELEMENT cost (#PCDATA)>

<!ELEMENT directorref (#PCDATA)>
<!ATTLIST directorref target IDREF #REQUIRED>

<!ELEMENT movie-stars (actor+)>
<!ELEMENT actor (name)>
<!ELEMENT name (#PCDATA)>

<!ELEMENT alldirectors (director+)>
<!ELEMENT director (#PCDATA)>
<!ATTLIST director destination ID #REQUIRED>

<!ELEMENT allstudios (studio+)>
<!ELEMENT studio (#PCDATA)>
<!ATTLIST studio destination ID #REQUIRED>

=== alexgeorgiew/XML_Project_FMI/movies.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE movies SYSTEM "validation.dtd">

<movies>
	<movie>
		<title>The Godfather</title>
		<image>&godfatherpic;</image>
		<year></year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
	<movie>
		<title> </title>
		<image></image>
		<year> </year>
		<genre> </genre>
		<production>
			<studio> </studio>
			<cost> </cost>
		</production>
		<director> </director>
		<movie-stars>
			<actor>
				<name> </name>
			</actor>
		</movie-stars>
	</movie>
</movies>
